{
    'name': 'MIS-Reports',
    'version': '13.0.0.1',
    'summary': """MIS Reports""",
    'category': 'Report',
    'author': 'Hafeel Salim, hafeel.salim@gmail.com',
    'company': 'mindinfosys.com, UAE',
    'description': 'Report Customization',
    'website': 'www.mindinfosys.com',
    'depends': ['base', 'account','sale', 'purchase'],
    'data': [
        'reports/invoice_report_templates.xml',
#        'reports/report_list.xml',
#        'reports/purchase_report_templates.xml',
        'reports/payment_report_template.xml',
        'reports/sale_template.xml',
        'reports/journal_report_templates.xml',
        'reports/report_list.xml',
        'data/mail_template_data_notpaid_invoice.xml',
        'data/mail_template_data_notpaid_invoice_summary.xml',
        'data/ir_cron.xml',
    ],
    'demo': [],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}